Remove libglvnd when using virtual/mesa
Fixes the following build error:

 $ bitbake dac-image-wayland-egl-test
 WARNING: You have included the meta-virtualization layer, but 'virtualization' has not been enabled in your DISTRO_FEATURES. Some bbappend files may not take effect. See the meta-virtualization README for details on enabling virtualization support.
 Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:00
 Loaded 4099 entries from dependency cache.
 Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:01
 Parsing of 2697 .bb files complete (2690 cached, 7 parsed). 4099 targets, 347 skipped, 0 masked, 0 errors.
 WARNING: No recipes available for:
  /data/dwrobel1/yocto/wpewebkit-1/build/../meta-clang/recipes-core/busybox/busybox_1.32.%.bbappend
 NOTE: Resolving any missing task queue dependencies
 ERROR: Nothing RPROVIDES 'libglvnd' (but /data/dwrobel1/yocto/wpewebkit-1/build/../meta-dac-sdk/recipes-example/images/dac-image-wayland-egl-test.bb RDEPENDS on or otherwise requires it)
 libglvnd was skipped: PREFERRED_PROVIDER_virtual/mesa set to mesa, not libglvnd
 NOTE: Runtime target 'libglvnd' is unbuildable, removing...
 Missing or unbuildable dependency chain was: ['libglvnd']
 ERROR: Required build target 'dac-image-wayland-egl-test' has no buildable providers.
 Missing or unbuildable dependency chain was: ['dac-image-wayland-egl-test', 'libglvnd']

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>