Fix building packages which depends on mesa vulkan
Fixes building wpewebkit 2.30.5:

 ERROR: Nothing RPROVIDES 'mesa-vulkan-drivers' (but /data/dwrobel1/yocto/wpewebkit-1/build/../meta/recipes-graphics/vulkan/vulkan-loader_1.1.126.0.bb RDEPENDS on or otherwise requires it)
 NOTE: Runtime target 'mesa-vulkan-drivers' is unbuildable, removing...
 Missing or unbuildable dependency chain was: ['mesa-vulkan-drivers']
 NOTE: Runtime target 'gstreamer1.0-plugins-bad-meta' is unbuildable, removing...
 Missing or unbuildable dependency chain was: ['gstreamer1.0-plugins-bad-meta', 'vulkan-loader', 'mesa-vulkan-drivers']
 NOTE: Runtime target 'cog' is unbuildable, removing...
 Missing or unbuildable dependency chain was: ['cog', 'wpewebkit', 'gstreamer1.0-plugins-bad-meta', 'vulkan-loader', 'mesa-vulkan-drivers']
 ERROR: Required build target 'core-image-minimal' has no buildable providers.
 Missing or unbuildable dependency chain was: ['core-image-minimal', 'cog', 'wpewebkit', 'gstreamer1.0-plugins-bad-meta', 'vulkan-loader', 'mesa-vulkan-drivers']

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>